/*
@overview Uninstall ownership contract for init's generated presentation prompt. ~45 lines.
READING GUIDE: Start at TestThePurgeOwnsTheGeneratedAgentPrompt.
MAIN FLOW: generated prompt.md -> ownedPaths -> lifecycle purge -> file removed.
PUBLIC API: None; this file tests CLI-owned installation inventory.
INTERNALS: TestThePurgeOwnsTheGeneratedAgentPrompt.
@exports
@deps os/path/filepath/testing, internal lifecycle
*/
package cli

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/thellmwhisperer/la-roca/internal/lifecycle"
)

// -- 1/1 CORE · TestThePurgeOwnsTheGeneratedAgentPrompt -- <- START HERE

func TestThePurgeOwnsTheGeneratedAgentPrompt(t *testing.T) {
	paths := resolvedIn(t, t.TempDir())
	prompt := filepath.Join(dirOf(paths.DB), "prompt.md")
	if err := os.MkdirAll(filepath.Dir(prompt), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(prompt, []byte("generated by init"), 0o600); err != nil {
		t.Fatal(err)
	}

	report := lifecycle.Plan{Owned: ownedPaths(paths), DataDir: dirOf(paths.DB)}.Apply()
	if _, err := os.Stat(prompt); !os.IsNotExist(err) {
		t.Fatalf("generated prompt survived purge: %v", err)
	}
	for _, kept := range report.Kept {
		if kept.Path == prompt {
			t.Fatalf("generated prompt reported as operator-owned: %s", kept.Reason)
		}
	}
}

// -/ 1/1
