package service

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"

	"github.com/thellmwhisperer/la-roca/internal/ingest"
	"github.com/thellmwhisperer/la-roca/internal/provider"
)

// What doctor says about a provider's credential. Presence, never the value:
// and it is enforced by there being no
// field that could hold it.
const (
	CredentialPresent   = "present"
	CredentialAbsent    = "absent"
	CredentialNotNeeded = "not needed"
)

// DoctorReport is the installation's diagnosis: where its data is, what it
// understood of its configuration, and which model is going to answer.
//
// It is what an operator reads before opening an issue, so every no carries its
// remedy; a diagnosis that names only the failure forces the operator to read
// code.
type DoctorReport struct {
	Version    string `json:"version"`
	SourceSHA  string `json:"source_sha"`
	DBPath     string `json:"-"`
	ConfigPath string `json:"config_path,omitempty"`
	// ConfigExists tells "there is no file, these are the defaults" apart from
	// "there is a file and this is what it says".
	ConfigExists bool     `json:"config_exists"`
	Memories     int      `json:"memories"`
	Bedrock      *Bedrock `json:"bedrock"`
	// DetectedAgents are the runtimes whose routes or stores exist on this machine.
	DetectedAgents []string `json:"detected_agents"`

	// Providers are in the declared order, each with its verdict.
	Providers []DoctorProvider `json:"providers"`
	// Titular is the one that is going to answer: the first available in the
	// order. Empty means no model is available.
	Titular string `json:"titular_provider,omitempty"`
	// Interpreters are the providers declared for the second inference, each
	// with the same verdict the main ones get. Empty is an installation that
	// does not split the two inferences, which is the default.
	Interpreters []DoctorProvider `json:"interpreters,omitempty"`
	// InterpretTitular is the one that is going to read the result rows. Empty
	// with interpreters declared means none of them is available and the rows go
	// to whoever writes the SQL, which is the decision an operator who split
	// them for privacy has to be able to see.
	InterpretTitular string `json:"interpret_provider,omitempty"`
	// ModelDisabled says the operator turned the model off on purpose, which is
	// not the same as having none available.
	ModelDisabled bool     `json:"model_disabled,omitempty"`
	Warnings      []string `json:"warnings,omitempty"`
	// PromptPath is the presentation block generated by init for a human to
	// paste into agent instructions. Roca never edits those files itself.
	PromptPath   string `json:"prompt_path"`
	PromptExists bool   `json:"prompt_exists"`
}

// DoctorProvider is one provider's verdict.
type DoctorProvider struct {
	Name  string `json:"provider"`
	Ready bool   `json:"ready"`
	Model string `json:"model,omitempty"`
	// Reason and Action are why it does not serve and what to do about it.
	Reason string `json:"reason,omitempty"`
	Action string `json:"action,omitempty"`
	// Credential is presence only. There is no field for the value on purpose.
	Credential string `json:"credential"`
}

type CredentialHolder interface {
	HasCredential() bool
}

func (s *Service) Doctor(ctx context.Context) (DoctorReport, error) {
	bedrock, err := s.bedrock(ctx)
	if err != nil {
		return DoctorReport{}, err
	}
	cascade := s.opts.Providers
	promptPath := filepath.Join(s.dataDir(), "prompt.md")
	promptInfo, promptErr := os.Stat(promptPath)
	report := DoctorReport{
		Version:        s.opts.Version,
		SourceSHA:      s.opts.Commit,
		DBPath:         s.db.Path(),
		ConfigPath:     s.opts.ConfigPath,
		ConfigExists:   s.opts.ConfigExists,
		ModelDisabled:  cascade.Disabled,
		Warnings:       cascade.Warnings,
		Memories:       s.countOf(ctx, "memories"),
		Bedrock:        bedrock,
		DetectedAgents: ingest.DetectAgents(s.opts.Sources),
		PromptPath:     promptPath,
		PromptExists:   promptErr == nil && promptInfo.Mode().IsRegular(),
	}

	report.Providers, report.Titular = verdicts(ctx, cascade)
	// The second inference gets the same diagnosis as the first, and only when
	// the operator declared one: an installation that does not split the two
	// inferences has no second decision to report.
	report.Interpreters, report.InterpretTitular = verdicts(ctx, s.opts.Interpreters)
	return report, nil
}

// Bedrock is the oldest valid moment in the ingested corpus. Project is best
// effort: exchanges inherit it from their session, while a memory may carry it
// directly.
type Bedrock struct {
	Timestamp string `json:"timestamp"`
	Project   string `json:"project,omitempty"`
}

func (s *Service) bedrock(ctx context.Context) (*Bedrock, error) {
	const query = `
		WITH candidates(timestamp, project) AS (
			SELECT started_at, project FROM sessions WHERE julianday(started_at) IS NOT NULL
			UNION ALL
			SELECT e.human_timestamp, s.project FROM exchanges e
			LEFT JOIN sessions s ON s.session_id = e.session_id
			WHERE julianday(e.human_timestamp) IS NOT NULL
			UNION ALL
			SELECT e.agent_timestamp, s.project FROM exchanges e
			LEFT JOIN sessions s ON s.session_id = e.session_id
			WHERE julianday(e.agent_timestamp) IS NOT NULL
			UNION ALL
			SELECT created_at, project FROM memories WHERE julianday(created_at) IS NOT NULL
		), floor(value) AS (SELECT MIN(julianday(timestamp)) FROM candidates)
		SELECT c.timestamp, COALESCE(c.project, '')
		FROM candidates c, floor
		WHERE julianday(c.timestamp) = floor.value
		ORDER BY c.project IS NULL, c.project
		LIMIT 1`
	var result Bedrock
	err := s.db.SQL().QueryRowContext(ctx, query).Scan(&result.Timestamp, &result.Project)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read corpus bedrock: %w", err)
	}
	return &result, nil
}

// verdicts is one cascade diagnosed: every provider with its verdict, in the
// declared order, and the first available one.
func verdicts(ctx context.Context, cascade provider.Cascade) ([]DoctorProvider, string) {
	var reported []DoctorProvider
	var titular string
	for i, attempt := range cascade.Diagnose(ctx) {
		reported = append(reported, DoctorProvider{
			Name:       attempt.Name,
			Ready:      attempt.Ready,
			Model:      attempt.ModelID,
			Reason:     attempt.Reason,
			Action:     attempt.Action,
			Credential: credentialOf(cascade.Providers[i]),
		})
		if attempt.Ready && titular == "" {
			titular = attempt.Name
		}
	}
	return reported, titular
}

func credentialOf(p provider.Provider) string {
	holder, holds := p.(CredentialHolder)
	if !holds {
		return CredentialNotNeeded
	}
	if holder.HasCredential() {
		return CredentialPresent
	}
	return CredentialAbsent
}
