package service

import (
	"context"
	"os"
	"path/filepath"

	"github.com/thellmwhisperer/la-roca/internal/ingest"
	"github.com/thellmwhisperer/la-roca/internal/provider"
)

// What doctor says about a provider's credential. Presence, never the value:
// and it is enforced by there being no
// field that could hold it.
const (
	CredentialPresent   = "present"
	CredentialAbsent    = "absent"
	CredentialNotNeeded = "not needed"
)

// DoctorReport is the installation's diagnosis: where its data is, what it
// understood of its configuration, and which model is going to answer.
//
// It is what an operator reads before opening an issue, so every no carries its
// remedy; a diagnosis that names only the failure forces the operator to read
// code.
type DoctorReport struct {
	Version    string `json:"version"`
	SourceSHA  string `json:"source_sha"`
	DBPath     string `json:"-"`
	ConfigPath string `json:"config_path,omitempty"`
	// ConfigExists tells "there is no file, these are the defaults" apart from
	// "there is a file and this is what it says".
	ConfigExists bool `json:"config_exists"`
	Memories     int  `json:"memories"`
	// DetectedAgents are the runtimes whose routes or stores exist on this machine.
	DetectedAgents []string `json:"detected_agents"`

	// Providers are in the declared order, each with its verdict.
	Providers []DoctorProvider `json:"providers"`
	// Titular is the one that is going to answer: the first available in the
	// order. Empty means no model is available.
	Titular string `json:"titular_provider,omitempty"`
	// ModelDisabled says the operator turned the model off on purpose, which is
	// not the same as having none available.
	ModelDisabled bool     `json:"model_disabled,omitempty"`
	Warnings      []string `json:"warnings,omitempty"`
	// PromptPath is the presentation block generated by init for a human to
	// paste into agent instructions. Roca never edits those files itself.
	PromptPath   string `json:"prompt_path"`
	PromptExists bool   `json:"prompt_exists"`
}

// DoctorProvider is one provider's verdict.
type DoctorProvider struct {
	Name  string `json:"provider"`
	Ready bool   `json:"ready"`
	Model string `json:"model,omitempty"`
	// Reason and Action are why it does not serve and what to do about it.
	Reason string `json:"reason,omitempty"`
	Action string `json:"action,omitempty"`
	// Credential is presence only. There is no field for the value on purpose.
	Credential string `json:"credential"`
}

type CredentialHolder interface {
	HasCredential() bool
}

func (s *Service) Doctor(ctx context.Context) (DoctorReport, error) {
	cascade := s.opts.Providers
	promptPath := filepath.Join(s.dataDir(), "prompt.md")
	promptInfo, promptErr := os.Stat(promptPath)
	report := DoctorReport{
		Version:        s.opts.Version,
		SourceSHA:      s.opts.Commit,
		DBPath:         s.db.Path(),
		ConfigPath:     s.opts.ConfigPath,
		ConfigExists:   s.opts.ConfigExists,
		ModelDisabled:  cascade.Disabled,
		Warnings:       cascade.Warnings,
		Memories:       s.countOf(ctx, "memories"),
		DetectedAgents: ingest.DetectAgents(s.opts.Sources),
		PromptPath:     promptPath,
		PromptExists:   promptErr == nil && promptInfo.Mode().IsRegular(),
	}

	attempts := cascade.Diagnose(ctx)
	for i, attempt := range attempts {
		report.Providers = append(report.Providers, DoctorProvider{
			Name:       attempt.Name,
			Ready:      attempt.Ready,
			Model:      attempt.ModelID,
			Reason:     attempt.Reason,
			Action:     attempt.Action,
			Credential: credentialOf(cascade.Providers[i]),
		})
		if attempt.Ready && report.Titular == "" {
			report.Titular = attempt.Name
		}
	}
	return report, nil
}

func credentialOf(p provider.Provider) string {
	holder, holds := p.(CredentialHolder)
	if !holds {
		return CredentialNotNeeded
	}
	if holder.HasCredential() {
		return CredentialPresent
	}
	return CredentialAbsent
}
