package service

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/thellmwhisperer/la-roca/internal/ingest"
	"github.com/thellmwhisperer/la-roca/internal/provider"
)

// DoctorReport is the installation's diagnosis: where its data is, what it
// understood of its configuration, and which model is going to answer.
//
// It is what an operator reads before opening an issue, so every no carries its
// remedy; a diagnosis that names only the failure forces the operator to read
// code.
type DoctorReport struct {
	Version    string `json:"version"`
	SourceSHA  string `json:"source_sha"`
	DBPath     string `json:"-"`
	ConfigPath string `json:"config_path,omitempty"`
	// ConfigExists tells "there is no file, these are the defaults" apart from
	// "there is a file and this is what it says".
	ConfigExists bool     `json:"config_exists"`
	Memories     int      `json:"memories"`
	Bedrock      *Bedrock `json:"bedrock"`
	// DetectedAgents are the runtimes whose routes or stores exist on this machine.
	DetectedAgents []string `json:"detected_agents"`
	// DetectedModelBinaries and MissingModelBinaries describe shipped agent CLI
	// transports independently of the configured order.
	DetectedModelBinaries []string `json:"detected_model_binaries"`
	MissingModelBinaries  []string `json:"missing_model_binaries"`
	// FactoryDefaultProvider is the provider selected by the PATH-built order.
	// It stays empty when the operator supplied an order or none is ready.
	FactoryDefault         bool   `json:"factory_default"`
	FactoryDefaultProvider string `json:"factory_default_provider,omitempty"`

	// Providers are in the declared order, each with its verdict.
	Providers []DoctorProvider `json:"providers"`
	// Titular is the one that is going to answer: the first available in the
	// order. Empty means no model is available.
	Titular string `json:"titular_provider,omitempty"`
	// Interpreters are the providers declared for the second inference, each
	// with the same verdict the main ones get. Empty is an installation that
	// does not split the two inferences, which is the default.
	Interpreters []DoctorProvider `json:"interpreters,omitempty"`
	// InterpretTitular is the one that is going to read the result rows. Empty
	// with interpreters declared means none of them is available and the rows go
	// to whoever writes the SQL, which is the decision an operator who split
	// them for privacy has to be able to see.
	InterpretTitular string `json:"interpret_provider,omitempty"`
	// Explorers are the optional providers declared for deep investigation.
	// Empty means deep mode follows interpretation order and then main order.
	Explorers []DoctorProvider `json:"explorers,omitempty"`
	// ExploreTitular is the first available provider in explore_order.
	ExploreTitular string `json:"explore_provider,omitempty"`
	// ModelDisabled says the operator turned the model off on purpose, which is
	// not the same as having none available.
	ModelDisabled bool     `json:"model_disabled,omitempty"`
	Warnings      []string `json:"warnings,omitempty"`
	// LayerRepairs are exact commands that register every runtime layer the
	// catalogue does not currently know.
	LayerRepairs []string `json:"layer_repairs,omitempty"`
	// PromptPath is the presentation block generated by init for a human to
	// paste into agent instructions. Roca never edits those files itself.
	PromptPath   string `json:"prompt_path"`
	PromptExists bool   `json:"prompt_exists"`
	// CapabilityProposals are open post-update configuration choices. The CLI
	// fills them from the reconciliation registry before rendering this report.
	CapabilityProposals []string `json:"capability_proposals,omitempty"`
}

// DoctorProvider is one provider's verdict.
type DoctorProvider struct {
	Name  string `json:"provider"`
	Ready bool   `json:"ready"`
	Model string `json:"model,omitempty"`
	// Reason and Action are why it does not serve and what to do about it.
	Reason string `json:"reason,omitempty"`
	Action string `json:"action,omitempty"`
}

func (s *Service) Doctor(ctx context.Context) (DoctorReport, error) {
	if _, err := s.ensureSchema(ctx); err != nil {
		return DoctorReport{}, err
	}
	bedrock, err := s.bedrock(ctx)
	if err != nil {
		return DoctorReport{}, err
	}
	cascade := s.opts.Providers
	promptPath := filepath.Join(s.dataDir(), "prompt.md")
	promptInfo, promptErr := os.Stat(promptPath)
	report := DoctorReport{
		Version:               s.opts.Version,
		SourceSHA:             s.opts.Commit,
		DBPath:                s.db.Path(),
		ConfigPath:            s.opts.ConfigPath,
		ConfigExists:          s.opts.ConfigExists,
		ModelDisabled:         cascade.Disabled,
		Warnings:              cascade.Warnings,
		Memories:              s.memoryCount(ctx),
		Bedrock:               bedrock,
		DetectedAgents:        ingest.DetectAgents(s.opts.Sources),
		DetectedModelBinaries: append([]string(nil), cascade.DetectedBinaries...),
		FactoryDefault:        cascade.FactoryDefault,
		PromptPath:            promptPath,
		PromptExists:          promptErr == nil && promptInfo.Mode().IsRegular(),
	}
	report.MissingModelBinaries = provider.MissingCommandPresets(cascade.DetectedBinaries)
	unregistered, err := s.unregisteredLayers(ctx)
	if err != nil {
		return DoctorReport{}, err
	}
	for _, name := range unregistered {
		report.LayerRepairs = append(report.LayerRepairs,
			"roca layers add "+shellQuoted(name)+" --db-path "+shellQuoted(report.DBPath))
	}

	report.Providers, report.Titular = verdicts(ctx, cascade)
	if cascade.FactoryDefault {
		report.FactoryDefaultProvider = report.Titular
	}
	// The second inference gets the same diagnosis as the first, and only when
	// the operator declared one: an installation that does not split the two
	// inferences has no second decision to report.
	report.Interpreters, report.InterpretTitular = verdicts(ctx, s.opts.Interpreters)
	report.Explorers, report.ExploreTitular = verdicts(ctx, s.opts.Explorers)
	return report, nil
}

func shellQuoted(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}

// Bedrock is the oldest valid moment in the ingested corpus. Project is best
// effort: exchanges inherit it from their session, while a memory may carry it
// directly.
type Bedrock struct {
	Timestamp string `json:"timestamp"`
	Project   string `json:"project,omitempty"`
}

func (s *Service) bedrock(ctx context.Context) (*Bedrock, error) {
	candidate := func(schema string) string {
		prefix := ""
		if schema != "" {
			prefix = quoteSchema(schema) + "."
		}
		return fmt.Sprintf(`
			SELECT started_at, project FROM %[1]ssessions WHERE julianday(started_at) IS NOT NULL
			UNION ALL
			SELECT e.human_timestamp, s.project FROM %[1]sexchanges e
			LEFT JOIN %[1]ssessions s ON s.session_id = e.session_id
			WHERE julianday(e.human_timestamp) IS NOT NULL
			UNION ALL
			SELECT e.agent_timestamp, s.project FROM %[1]sexchanges e
			LEFT JOIN %[1]ssessions s ON s.session_id = e.session_id
			WHERE julianday(e.agent_timestamp) IS NOT NULL
			UNION ALL
			SELECT created_at, project FROM %[1]smemories WHERE julianday(created_at) IS NOT NULL`, prefix)
	}
	parts := []string{candidate("")}
	for _, database := range s.resident {
		if database.Name == rocaCorpusPluginName {
			parts = append(parts, candidate(database.Schema))
			break
		}
	}
	query := `
		WITH candidates(timestamp, project) AS (
			` + strings.Join(parts, " UNION ALL ") + `
		), floor(value) AS (SELECT MIN(julianday(timestamp)) FROM candidates)
		SELECT c.timestamp, COALESCE(c.project, '')
		FROM candidates c, floor
		WHERE julianday(c.timestamp) = floor.value
		ORDER BY c.project IS NULL, c.project
		LIMIT 1`
	connection, attached, err := s.openQueryConnection(ctx)
	if err != nil {
		return nil, fmt.Errorf("open corpus for bedrock: %w", err)
	}
	defer closeQueryConnection(connection, attached)
	var result Bedrock
	err = connection.QueryRowContext(ctx, query).Scan(&result.Timestamp, &result.Project)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read corpus bedrock: %w", err)
	}
	return &result, nil
}

func (s *Service) memoryCount(ctx context.Context) int {
	statement := "SELECT COUNT(*) FROM memories"
	for _, database := range s.resident {
		if database.Name == rocaCorpusPluginName {
			statement += " UNION ALL SELECT COUNT(*) FROM " + quoteSchema(database.Schema) + ".memories"
			break
		}
	}
	connection, attached, err := s.openQueryConnection(ctx)
	if err != nil {
		return 0
	}
	defer closeQueryConnection(connection, attached)
	rows, err := connection.QueryContext(ctx, statement)
	if err != nil {
		return 0
	}
	defer rows.Close()
	total := 0
	for rows.Next() {
		var count int
		if rows.Scan(&count) != nil {
			return 0
		}
		total += count
	}
	return total
}

// verdicts is one cascade diagnosed: every provider with its verdict, in the
// declared order, and the first available one.
func verdicts(ctx context.Context, cascade provider.Cascade) ([]DoctorProvider, string) {
	var reported []DoctorProvider
	var titular string
	for _, attempt := range cascade.Diagnose(ctx) {
		reported = append(reported, DoctorProvider{
			Name:   attempt.Name,
			Ready:  attempt.Ready,
			Model:  attempt.ModelID,
			Reason: attempt.Reason,
			Action: attempt.Action,
		})
		if attempt.Ready && titular == "" {
			titular = attempt.Name
		}
	}
	return reported, titular
}
