package cli

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/thellmwhisperer/la-roca/internal/distribution/lifecycle"
)

func TestThePurgeOwnsTheGeneratedAgentPrompt(t *testing.T) {
	paths := resolvedIn(t, t.TempDir())
	prompt := filepath.Join(dirOf(paths.DB), "prompt.md")
	if err := os.MkdirAll(filepath.Dir(prompt), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(prompt, []byte("generated by init"), 0o600); err != nil {
		t.Fatal(err)
	}

	report := lifecycle.Plan{Owned: ownedPaths(paths), DataDir: dirOf(paths.DB)}.Apply()
	if _, err := os.Stat(prompt); !os.IsNotExist(err) {
		t.Fatalf("generated prompt survived purge: %v", err)
	}
	for _, kept := range report.Kept {
		if kept.Path == prompt {
			t.Fatalf("generated prompt reported as operator-owned: %s", kept.Reason)
		}
	}
}
